### ISSUE TITLE
Unable to resize when plugin enabled 

### ISSUE THREAD

**Issue by gigili** [kek91/StatusBarExtended#9]
When trying to resize the fman window size I'm only able to make it wider but not smaller then the bars default size. And if I disable the plugin and resize the window and then enable the plugin again it resizes the whole window again to the bars default size.

I have uploaded a youtube example window showing this error
https://youtu.be/Dxa1CC3koWc

**Comment by kek91** [comment]
Thanks for the detailed description and video! I'll take a look at it this weekend

**Comment by kek91** [comment]
Hi again
Take a look at commit 3ca99ed528343f113b723d343b81c97b4c66ef6d , I've done some adjustments so now it's possible to adjust the window to fit the 3 columns on both panes. I suppose that should be ok for most situations.

It's still not responsive as I've wanted to do for a while (ref issue #7 ), but at least it's a small improvement.

The problem is as you can imagine that the status bar refuses to resize smaller than the width of the text. I'll try to come up with some solution to get the current width of the window and if width < X then do some text adjustments to allow for smaller resizing.
An other solution could be to let the Qt Statusbar itself just ignore the text width and resize even if the text goes out of view. This has to be implemented in the core plugin by @mherrmann though

![Screenshot Ubuntu 16.04](https://raw.githubusercontent.com/kek91/StatusBarExtended/master/fman-plugin-ubuntu-2.9.png)

**Comment by kek91** [comment]
If anyone wants to take a stab at this, what needs to be done:

In file `StatusBarExtended/statusbarextended/__init__.py`:

- Calculate current width of fman window. This is not implemented in the fman API so you'll have to figure it out using the Qt framework, but this may or may not be supported by fman eventually because of PyQt licensing

- If the width is lesser than X (take some tests and figure out, maybe ~400 px), then adjust the output in `show_status_message()` on line 62 to take up lesser space. i.e, change 

`show_status_message('{:<25}  {:>140}'.format(statusbar_pane1, statusbar_pane2), 5000)` 

to

`show_status_message('{:<25}  {:>100}'.format(statusbar_pane1, statusbar_pane2), 5000)`

- Repeat the step above for an even smaller width to make it more responsive... kind of like CSS media queries.

**Comment by mherrmann** [comment]
fman should allow resizing the window to a width smaller than the status bar. I've created a [card](https://trello.com/c/IbU32rNx/136-can-t-resize-fman-to-width-status-bar-eg-when-statusbarextended-is-installed) for this.

**Comment by gigili** [comment]
How about allowing the text to overlap ?

For instance if there is enough space display text as is, but if there isn't overlap text or maybe disable one side of the text (usually the right one is with less needed info). 

Or if you disable one side of the text to be displayed than the one left could probably display all the info it has, and in the case that there isn't enough space it would trim the text to fit the width and add ... at the end, till there is no space left and all that is written is just ...

Any opinions on this ?

**Comment by mherrmann** [comment]
I'm not sure I fully understand what you mean by "overlap" Igor. I think fman should simply "cut off" text that isn't visible. I don't even think the three "..." are really necessary.

I believe it's also an issue for the plugin that fman's API doesn't give a way of saying "display this text below the _right_ pane". You use `'{:>140}'.format(...)` to shift text to the right Kim. But it would probably be best if you could just say `self.pane.show_status_message(...)`, no?

**Comment by kek91** [comment]
Yeah the right-align of text with `'{:>140}'.format(...)` doesn't really work well because we have to specify it in pixels, not % width of parent container.. so it'll always look ugly one way or another.

Yes @mherrmann , if the statusbar is divided so we can use `self.pane.show_status_message()` for each pane that would practically solve the problem. Even better if fman allows to resize window smaller than statusbar.

For a temporary solution I agree with you @gigili , simply showing output for only the current active pane would also kind of solve the problem because the output would be a lot less. 

If we want to "gracefully" reduce the output text to fit the window, we'd have to implement some kind of "media queries" to get the current fman window width and if it's below X pixels then adjust the output. 
I think we must fiddle with PyQt QWidget though to get the width of fman window.

On that thought I just got an idea, perhaps fman could implement another API method for showing application info; `fman.info()`. Some method suggestions: `fman.info().window_size_x`, `fman.info().window_size_y`, `fman.info().username` , `fman.info().datadir` , `fman.info().installdir`.

**Comment by mherrmann** [comment]
`self.pane.show_status_message()` sounds like a good solution. I've added a [card](https://trello.com/c/fKTKr8xj/140-api-add-self-pane-show-status-message-so-it-s-possible-to-show-not-just-global-status-messages-but-also-pane-specific-ones) for it :-)

Relying on PyQt may work at the moment, but is not officially supported. Any PyQt-related functions may break at any time. I would strongly advise against relying on PyQt. I once wrote this about it:

> I don't currently expose Qt internals in fman's API. The two reasons for this are a) that I'm not sure I'm allowed to give you access to them for legal reasons. I am using a commercial license of PyQt and I'm not 100% sure whether I will be allowed to give you access to its API without requiring you to purchase a commercial license as well. The second reason b) is that it's still early in fman's plugin API and I want to keep my options open. For instance, Sublime Text said in one of its release notes that it now runs plugins in their own process. Apparently some plugins used to crash Sublime Text. If I expose Qt internals in fman's API, then I will never be able to run plugins in their own processes. That's why up until now I've taken great care to "hide" any references to Qt from fman's API.

The path to the data directory is available as `DATA_DIRECTORY`. The path to fman's executable (and thus to the install dir) via:

```
import sys
sys.executable
```

For `username`, do you mean the OS user name? If yes, that's

```
from getpass import getuser
getuser()
```

Alternatively, licensed users now have a license key file which contains their email address. This could be read out as well.

I'm not sure about `window_size_x`. It feels too low-level. If I understand correctly, you want to use it to determine how much text to display. But then you would need to know how many pixels your text takes up. And what if the user has some weird font size? Or a high DPI display that renders twice the amount of pixels in any direction? It's a difficult subject.

My suggestion (which you're of course free to dismiss) is to display the information you deem most important first in the text. Eg. if you think the number of dirs/files is more important than whether hidden files are being shown, write `Dirs: 14, Files: 2, Hidden Files: Hide` instead of `Hidden Files: Hide, Dirs: 14, Files: 2`. Then, when fman is resized too narrowly, the `Hidden Files` bit gets cut off naturally without you having to worry what to display and what not. But of course it's just an idea and I don't know if it will work for your use cases. Feel free to tell me off ;-)

**Comment by kek91** [comment]
Awesome, already voted on the card :-)

Yeah I don't want to fiddle with PyQt too much, so I figured a method for showing debug information etc might be useful for you and other plugin developers. So instead of importing other libraries we could just use `info()` or `debug()` from fman module.

But yes, for the few examples I mentioned it's probably not worth the extra overhead and work involved. But good idea for another plugin though, **a plugin to debug plugins for plugin developers** :) 

Regarding your suggestion on the text prioritization. You're right, that never crossed my mind actually... no need to overthink it :)

Conclusion for now: I'll change the plugin to show only output for the currently active/focused pane. When `show_status_message()` implements status bar for both panes I'll change the plugin back again

**Comment by mherrmann** [comment]
Heh a **plugin to debug plugins** is a cool idea ^^ I wonder how far one could take this...

I'll keep `.pane.show_status_message` in mind.

Cheers :)
M

**Comment by kek91** [comment]
So I did some changes now. 
- Show only output for current pane
- If no files are present in current directory, then omit "files: x" and "size: x" completely
- Visualize show_hidden_files status with an icon instead, checkmark for true and cross for false

Unfortunately it requires a folder refresh to trigger StatusBarExtended so just pressing TAB to change pane won't actually update the status bar. I'll put that in a new issue

I hope it fits the bill @gigili  :)

![new version](https://raw.githubusercontent.com/kek91/StatusBarExtended/master/fman-plugin-statusbarextended-v0.3.0.png)
